services:
  greet:
    container_name: inova_service
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8080:8080"
    networks:
      - internal
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "127.0.0.1:3010:3000"
    depends_on:
      - greet
    networks:
      - internal

  postgres:
    image: postgres:16
    container_name: inova_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal

volumes:
  postgres_data:

networks:
  internal:
    driver: bridge
