services:
  greet-test:
    container_name: greet_service_test
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    working_dir: /app
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_TEST_DB}?sslmode=disable"
    depends_on:
      - postgres-test
    networks:
      - testnet
    command: ["go", "test", "-v", "./tests/..."]

  postgres-test:
    image: postgres:16
    container_name: postgres_test_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_TEST_DB}
    ports:
      - "5433:5432"
    networks:
      - testnet
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:

networks:
  testnet:
    driver: bridge

